export const DB_AMBIENCE_WORDS = [
    // VERBS
    'marrying',
    'divorcing',
    'living',
    'drinking',
    'eating',
    'visiting',
    'talking',
    'laughing',
    'wanting',
    'searching',
    'finding',
    'working',
    'studying',
    'trying',
    'feeling',
    'leaving',
    'keeping',
    'letting go',
    'beginning',
    'starting',
    'playing',
    'living',
    'believing',
    'losing',
    'paying',
    'learning',
    'changing',
    'following',
    // NOUNS
    'love',
    'fate',
    'home',
    'memories',
    'memory',
    'history',
    'choices',
    'change',
    'changes',
    'revelations',
    'revelation',
]